### ISSUE TITLE
Undefined identifier `FT_Fixed` with FT_2_13

### ISSUE THREAD

**Issue by bagomot** [BindBC/bindbc-freetype#15]
Build error:
> source\ft\synth.d-mixin-15(18,2): Error: undefined identifier `FT_Fixed`
> source\ft\synth.d-mixin-15(19,2): Error: undefined identifier `FT_Fixed`
> source\ft\synth.d-mixin-15(27,17): Error: undefined identifier `FT_Fixed`
> source\ft\synth.d-mixin-15(29,17): Error: undefined identifier `FT_Fixed`

The error occurs with both static and dynamic linking.

OS: Windows 11 x64
Freetype: 2.13.2

dub.sdl:
```
dependency "bindbc-freetype" version="~>1.2.2"
libs "freetype"
versions "FT_2_13"
```

**Comment by ichordev** [comment]
Just released v1.2.3, which _should_ fix this. Please confirm whether you're still experiencing this issue after updating?
