### ISSUE TITLE
Can't find Freetype library

### ISSUE THREAD

**Issue by neilsf** [BindBC/bindbc-freetype#19]
Hi

On Ubuntu 22.04, I'm trying to install and run [dlangide](https://github.com/buggins/dlangide) that uses this library.
The error I'm getting is:

    2024-09-15 15:14:05.044 V  bindbc-freetype: Loading FreeType library
    2024-09-15 15:14:05.053 E  bindbc-freetype: cannot load freetype shared library: bindbc-freetype unable to find suitable library, v2_6 minimum required
    object.Exception@../../.dub/packages/dlangui/0.10.8/dlangui/src/dlangui/graphics/ftfonts.d(599): Cannot load freetype library

`bindbc-freetype` version: 1.2.6

Although I think I have freetype6 > 2.6 installed:

    neils@Home:~$ dpkg -l | grep freetype
    ii  libfreetype6:amd64                         2.11.1+dfsg-1ubuntu0.2                           amd64        FreeType 2 font engine, shared library files

Note: I have built freetype from source because the version coming from the Ubuntu repo is < 2.6. Interestingly, I've downloaded version 2.13 but the above shows 2.11.1.

Any tips on how to resolve? Thanks

**Comment by ichordev** [comment]
> Hi
> 
> On Ubuntu 22.04, I'm trying to install and run [dlangide](https://github.com/buggins/dlangide) that uses this library. The error I'm getting is:
> 
> ```
> 2024-09-15 15:14:05.044 V  bindbc-freetype: Loading FreeType library
> 2024-09-15 15:14:05.053 E  bindbc-freetype: cannot load freetype shared library: bindbc-freetype unable to find suitable library, v2_6 minimum required
> object.Exception@../../.dub/packages/dlangui/0.10.8/dlangui/src/dlangui/graphics/ftfonts.d(599): Cannot load freetype library
> ```

It looks like dlangui is trying to load the library correctly, so that's not the source issue at least.

> Note: I have built freetype from source because the version coming from the Ubuntu repo is < 2.6. Interestingly, I've downloaded version 2.13 but the above shows 2.11.1.
> 
> Any tips on how to resolve? Thanks

Would you be able to check what path FreeType 2.13 is installed into? It might be that the newer version is not in your system's library loading paths, or `ldconfig` needs to be run.

**Comment by neilsf** [comment]
My bad, I missed `ldconfig`.  Thanks a lot!
