### ISSUE TITLE
One FreeType module getting undefined identifiers for LINUX builds only.

### ISSUE THREAD

**Issue by WhatMeWorry** [BindBC/bindbc-freetype#2]
This is probably an issue only with Linux.   It works fine on Windows 10.

On my Ubuntu 18 system when I try to build a project with FreeType

dependency "bindbc-freetype"  version="~>0.4.1"
versions "FT_210"

I get:

/freetype/dynload.d ../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/package.d -vcolumns
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(24,19): Error: undefined identifier FT_Int32
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(25,20): Error: undefined identifier FT_UInt32
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(37,13): Error: undefined identifier FT_Error
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(37,13): Error: undefined identifier FT_Face
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(38,13): Error: undefined identifier FT_Error
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(38,13): Error: undefined identifier FT_Face
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(42,36): Error: undefined identifier pFT_Get_BDF_Charset_ID, did you mean variable FT_Get_BDF_Charset_ID?
../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(43,34): Error: undefined identifier pFT_Get_BDF_Property, did you mean variable FT_Get_BDF_Property?
FAIL ../../../.dub/packages/bindbc-freetype-0.4.1/bindbc-freetype/.dub/build/dynamic-debug-linux.posix-x86_64-ldc_2084-98EFDEFAB389223C22355F3FFA78A145/ BindBC_FT staticLibrary
ldc2 failed with exit code 1.
./../duball exited with code 2

I noticed ftbdf.d consists of one large version conditional, which would explain why it compiled and ran fine on a Windows system.

module bindbc.freetype.bind.ftbdf;
version(linux) {
    // all code
}

Hope it is not something I'm doing wrong.

**Comment by mdparker** [comment]
That's a combination of missing imports and a couple of typos in `ftbdf.d`, nothing you've done. I haven't tried to compile any of these packages on Linux yet. I need to make that a priority. Thanks for reporting all these issues.

These should all be fixed in v0.4.2. Run `dub upgrade` to get it.

**Comment by WhatMeWorry** [comment]
Still on the same Ubuntu system...

I didn't use dub upgrade but I did blow away all my local packages and just started from scratch.
Updated my dub.sdl to freetype 4.2. I'm now getting.

...
Checking for missing dependencies.
Using fixed selection gl3n 1.3.1
Using fixed selection bindbc-opengl 0.8.0
Using fixed selection bindbc-freetype 0.4.2
...
dub/packages/bindbc-freetype-0.4.2/bindbc-freetype/source/bindbc/freetype/dynload.d ../../../.dub/packages/bindbc-freetype-0.4.2/bindbc-freetype/source/bindbc/freetype/package.d -vcolumns
../../../.dub/packages/bindbc-freetype-0.4.2/bindbc-freetype/source/bindbc/freetype/bind/ftbdf.d(11,12): Error: module `freetype` is in file 'bindbc/freetype/freetype.d' which cannot be read
import path[0] = ../../../.dub/packages/bindbc-freetype-0.4.2/bindbc-freetype/source/
import path[1] = ../../../.dub/packages/bindbc-loader-0.2.1/bindbc-loader/source/
import path[2] = /home/generic/dlang/ldc-1.14.0/bin/../import
FAIL ../../../.dub/packages/bindbc-freetype-0.4.2/bindbc-freetype/.dub/build/dynamic-debug-linux.posix-x86_64-ldc_2084-98EFDEFAB389223C22355F3FFA78A145/ BindBC_FT staticLibrary
ldc2 failed with exit code 1.
./../duball exited with code 2

**Comment by mdparker** [comment]
Okay. Give me a few days and I'll install everything on my linux notebook and make sure it's building, loading and functioning. Then I'll let you know.

**Comment by WhatMeWorry** [comment]
No hurry.  I was able to get it to compile and run successfully with two small edits:

in ftbdf.d, changed lines 11, 12 from
import bindbc.freetype.freetype,
           bindbc.freetype.fttypes;
to
import bindbc.freetype.bind.freetype;
import bindbc.freetype.bind.fttypes;

And in line 65 of dynload.d changed
ret = loadFreetype(name.ptr);
to
ret = loadFreetype(name.ptr);

After that everything worked perfectly.  Hope this is of some small help.

**Comment by WhatMeWorry** [comment]
Have you been able to get back to this issue?  You've spoiled me by your previous quick response time. :)

**Comment by mdparker** [comment]
Sorry! I forgot all about it. I've got my Linux laptop in London with me, though, so I'll see if I can make time for it during the Hackathon on Saturday. If not, I can certainly take care of it in my hotel before I fly back to Korea next Wednesday.

**Comment by mdparker** [comment]
So the wi-fi at the Hackathon was slow and my wife was using both of the 2 devices Travelodge limited us to on their wi-fi. I'm back home now catching up on things and just got the fix for this pushed and tested in my Linux VM. It's in v0.5.0. Sorry for the delay!
