### ISSUE TITLE
Error: no property FT_210 for type FTSupport

### ISSUE THREAD

**Issue by CodeMyst** [BindBC/bindbc-freetype#4]
I added bindbc-freetype to my project and it fails to build with this message:
```
source\bindbc\freetype\bind\ftmodapi.d(45,25): Error: no property FT_210 for type FTSupport
```

i cloned this repo as well to test if its something with my project but nope, these bindings itself fail to build.

**Comment by mdparker** [comment]
Thanks. Fixed in 0.9.1.
